# NumPy arrays lab

Enter your code below each comment



In [1]:
import random
import numpy as np

Here is a list of the mileage (given in MPG) of students in my last class: 21.1, 26.6, 16.3, 33.7, 31.2, 52.0, 27.1

Create a NumPy array named 'mpg' from these values (use the given order).

In [2]:
mpg = np.array([21.1, 126.6, 16.3, 33.7, 31.2, 52.0, 27.1])

Create a new array x that has the same length as mpg but every value is 25.0  (use the NumPy size property of mpg).

In [3]:
x = np.array([25.0] * mpg.size)

print the mileage of the third student

In [4]:
print(mpg[2])

16.3


print the mileage of the last student

In [5]:
print(mpg[-1])

27.1


print the mileage of the first to the third students

print(mpg[0:3])

print the mileage of every other student, starting with the first

print(mpg[::2])

 Can you print the same mileages, but in reverse order?

print(mpg[::-1])

 make a copy of mpg, named mpg2

In [6]:
mpg2 = mpg.copy()

print the concatenation of mpg and mpg2


In [7]:
print(np.concatenate((mpg, mpg2), axis=0))

[ 21.1 126.6  16.3  33.7  31.2  52.   27.1  21.1 126.6  16.3  33.7  31.2
  52.   27.1]


print the data type (dtype) of mpg

In [8]:
mpg.dtype

dtype('float64')

add 5.0 to every element of mpg2

In [9]:
mpg2 + (5.0)

array([ 26.1, 131.6,  21.3,  38.7,  36.2,  57. ,  32.1])

Create a NumPy array 'miles' giving the distances each student has to travel to CSUMB.  The values are:

8.1, 5.4, 12.8, 42.1, 15.0, 22.2, 18.5

In [10]:
miles = np.array([8.1, 5.4, 12.8, 42.1, 15.0, 22.2, 18.5])

The gallons used by a student in a round trip to CSUMB is the round-trip distance divided by miles-per-gallon.  Using vectorized operations, compute the number of gallons used by each student in a round trip to CSUMB.  Assign the result to variable 'gallons'.


In [11]:
gallons = np.divide(miles, mpg)

 Create a boolean array that is True for every element of gallons that is less than 1.  Assign it to variable 'low_gas'.

In [12]:
low_gas = gallons < 1.0

Use a boolean mask to get the values in gallons that are less than 1

In [13]:
gallons[low_gas]

array([0.38388626, 0.04265403, 0.78527607, 0.48076923, 0.42692308,
       0.68265683])

Run the following line of code, which creates an array of a million random numbers between 0 and 1.

In [14]:
x = np.array([random.random() for _ in range(10000000)])

 write a python loop to compute the sum of the values in x

In [15]:
sum = 0 
for i in range(0, len(x)):
    sum += x[i]

Define a Python function named 'array_sum' that will return the sum of the specified NumPy array x.


In [16]:
def array_sum(nums):
    total = 0
    for i in range(0, len(x)):
        total += nums[i]
    return total

Measure how long it takes for your function to sum the elements of the big array x you defined earlier.

hint: use %timeit

In [17]:
%timeit array_sum(x)

1.26 s ± 67.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


now measure how long it takes to do the same thing using np.sum

In [18]:
%timeit np.sum(x)

4.65 ms ± 403 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


write code to show that slicing does not copy the input data

In [19]:
x = np.array([1,2,3,4,5])
y = x[:3]
y[0] = 0
print(x)
print(y)
# changes the original copy x

[0 2 3 4 5]
[0 2 3]


If you still have time, learn about some of the "magic commands" available in IPython.

https://ipython.org/ipython-doc/3/interactive/magics.html